title: kernelpony
description: "A Computer Science Blog"
author:
  name: "Zyra"
  email: "zyraryorks@gmail.com"
  url: "https://kernelpony.github.io/"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "kernelpony"
year : "2019"
